# younmh_templates.tcl : template Tcl file generated by Liberate 14.1.3.110 on ä¸? 2??17 20:25:51 CST 2016

#set_units -capacitance 1ff 
#set_units -leakage_power 1pw 
#set_units -timing 1ns
set_var slew_lower_rise 0.1
set_var slew_lower_fall 0.1
set_var slew_upper_rise 0.9
set_var slew_upper_fall 0.9

set_var measure_slew_lower_rise 0.1
set_var measure_slew_lower_fall 0.1
set_var measure_slew_upper_rise 0.9
set_var measure_slew_upper_fall 0.9

set_var delay_inp_rise 0.5
set_var delay_inp_fall 0.5
set_var delay_out_rise 0.5
set_var delay_out_fall 0.5

set_var def_arc_msg_level 0
set_var max_transition 1e-9
set_var min_transition 4e-13
set_var min_output_cap 4e-16

set cells { 
A2O1A1Ixp33_fin22 \
A2O1A1O1Ixp25_fin22 \
AND2x1_fin22 \
AND2x2_fin22 \
AND2x4_fin22 \
AND2x6_fin22 \
AND3x1_fin22 \
AND3x2_fin22 \
AND3x4_fin22 \
AND3x6_fin22 \
AND4x1_fin22 \
AND4x2_fin22 \
AND4x4_fin22 \
AND4x6_fin22 \
AND5x1_fin22 \
AND5x2_fin22 \
AO21x1_fin22 \
AO21x2_fin22 \
AO22x1_fin22 \
AO22x2_fin22 \
AO31x1_fin22 \
AO31x2_fin22 \
AO32x1_fin22 \
AO32x2_fin22 \
AO33x1_fin22 \
AO33x2_fin22 \
AO211x2_fin22 \
AO221x1_fin22 \
AO221x2_fin22 \
AO222x1_fin22 \
AO222x2_fin22 \
AO322x2_fin22 \
AO331x1_fin22 \
AO331x2_fin22 \
AO332x1_fin22 \
AO332x2_fin22 \
AO333x1_fin22 \
AO333x2_fin22 \
AOI21x1_fin22 \
AOI21xp5_fin22 \
AOI21xp25_fin22 \
AOI22x1_fin22 \
AOI22xp5_fin22 \
AOI22xp25_fin22 \
AOI31xp25_fin22 \
AOI31xp5_fin22 \
AOI32x1_fin22 \
AOI32xp25_fin22 \
AOI32xp33_fin22 \
AOI33x1_fin22 \
AOI33xp33_fin22 \
AOI211x1_fin22 \
AOI211x25_fin22 \
AOI221x1_fin22 \
AOI221xp25_fin22 \
AOI222xp25_fin22 \
AOI311xp33_fin22 \
AOI321xp25_fin22 \
AOI322xp25_fin22 \
AOI331xp33_fin22 \
AOI332xp33_fin22 \
AOI333xp33_fin22 \
ASYNC_reset_DFFHx1_fin22 \
ASYNC_set_DFFHx1_fin22 \
BUFx1_fin22 \
BUFx2_fin22 \
BUFx3_fin22 \
BUFx4_fin22 \
BUFx4f_fin22 \
BUFx5_fin22 \
BUFx6f_fin22 \
BUFx8_fin22 \
BUFx10_fin22 \
BUFx12_fin22 \
BUFx12f_fin22 \
BUFx16f_fin22 \
BUFx24_fin22 \
BUFxp5_fin22 \
DFFHQNx1_fin22 \
DFFHQNx2_fin22 \
DFFHQNx3_fin22 \
DFFHQx4_fin22 \
DFFLQNx1_fin22 \
DFFLQNx2_fin22 \
DFFLQNx3_fin22 \
DFFLQx4_fin22 \
DHLx1_fin22 \
DHLx2_fin22 \
DHLx3_fin22 \
DLLx1_fin22 \
DLLx2_fin22 \
DLLx3_fin22 \
FILLER_fin22 \
FAx1_fin22 \
HAx1_fin22 \
HAxp5_fin22 \
HB1xp5_fin22 \
HB2xp5_fin22 \
HB3xp5_fin22 \
HB4xp5_fin22 \
ICGx1_fin22 \
ICGx2_fin22 \
ICGx3_fin22 \
INVx1_fin22 \
INVx2_fin22 \
INVx3_fin22 \
INVx4_fin22 \
INVx5_fin22 \
INVx6_fin22 \
INVx8_fin22 \
INVx11_fin22 \
INVx13_fin22 \
INVxp5_fin22 \
MAJIxp5_fin22 \
MAJx2_fin22 \
MAJx3_fin22 \
MUX2x1_fin22 \
MUX2x2_fin22 \
NAND2x1_fin22 \
NAND2x1p5_fin22 \
NAND2x2_fin22 \
NAND2xp25_fin22 \
NAND2xp5_fin22 \
NAND2xp33_fin22 \
NAND3x1_fin22 \
NAND3x2_fin22 \
NAND3xp33_fin22 \
NAND4xp25_fin22 \
NAND4xp75_fin22 \
NAND4x1_fin22 \
NAND4x2_fin22 \
NAND5xp2_fin22 \
NOR2x1_fin22 \
NOR2x1p5_fin22 \
NOR2x2_fin22 \
NOR2xp25_fin22 \
NOR2xp5_fin22 \
NOR2xp33_fin22 \
NOR3x1_fin22 \
NOR3x2_fin22 \
NOR3xp33_fin22 \
NOR4xp25_fin22 \
NOR4xp75_fin22 \
NOR4x1_fin22 \
NOR4x2_fin22 \
NOR5xp2_fin22 \
O2A1O1Ixp33_fin22 \
O2A1O1Ixp5_fin22 \
OA21x2_fin22 \
OA22x2_fin22 \
OA31x2_fin22 \
OA33x2_fin22 \
OA211x1_fin22 \
OA211x2_fin22 \
OA221x1_fin22 \
OA221x2_fin22 \
OA222x1_fin22 \
OA222x2_fin22 \
OA331x1_fin22 \
OA331x2_fin22 \
OA332x1_fin22 \
OA332x2_fin22 \
OA333x1_fin22 \
OA333x2_fin22 \
OAI21x1_fin22 \
OAI21xp5_fin22 \
OAI21xp25_fin22 \
OAI22x1_fin22 \
OAI22xp5_fin22 \
OAI22xp25_fin22 \
OAI31xp5_fin22 \
OAI31xp25_fin22 \
OAI32x1_fin22 \
OAI32xp33_fin22 \
OAI32xp25_fin22 \
OAI33x1_fin22 \
OAI33xp33_fin22 \
OAI211x1_fin22 \
OAI211xp25_fin22 \
OAI221x1_fin22 \
OAI221xp25_fin22 \
OAI222xp25_fin22 \
OAI311xp33_fin22 \
OAI321xp25_fin22 \
OAI322xp25_fin22 \
OAI331xp33_fin22 \
OAI332xp33_fin22 \
OAI333xp33_fin22 \
OR2x1_fin22 \
OR2x2_fin22 \
OR2x4_fin22 \
OR2x6_fin22 \
OR3x1_fin22 \
OR3x2_fin22 \
OR3x4_fin22 \
OR4x1_fin22 \
OR4x2_fin22 \
OR4x4_fin22 \
OR5x1_fin22 \
OR5x2_fin22 \
OR5x4_fin22 \
SDFHx1_fin22 \
SDFHx2_fin22 \
SDFHx3_fin22 \
SDFHx4_fin22 \
SDFLx1_fin22 \
SDFLx2_fin22 \
SDFLx3_fin22 \
SDFLx4_fin22 \
TIEHIx1_fin22 \
TIELOx1_fin22 \
XNOR2x1_fin22 \
XNOR2x2_fin22 \
XNOR2xp5_fin22 \
XOR2x1_fin22 \
XOR2x2_fin22 \
XOR2xp5_fin22
}

# constraint
define_template -type constraint \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
		-index_2 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        constraint_fin32_7x7
define_template -type constraint \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
		-index_2 {0.0033 0.0066 0.132 0.264 0.528 1.056 2.112 } \
        constraint_fin22_7x7
define_template -type constraint \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
		-index_2 {0.0033 0.0066 0.132 0.264 0.528 1.056 2.112 } \
        constraint_fin21_7x7


# delay
	#fin32 delay
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0009 0.0018 0.0036 0.0072 0.0144 0.0288 0.0576 } \
        delay_fin32_7x7_x1
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00018 0.00036 0.00072 0.00144 0.00288 0.00576 0.01152 } \
        delay_fin32_7x7_xp2
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.000225 0.00045 0.0009 0.0018 0.0036 0.0072 0.0144 } \
        delay_fin32_7x7_xp25
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.000297 0.000594 0.001188 0.002376 0.004752 0.009504 0.019008 } \
        delay_fin32_7x7_xp33
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00045 0.0009 0.0018 0.0036 0.0072 0.0144 0.0288 } \
        delay_fin32_7x7_xp5
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.000603 0.001206 0.002412 0.004824 0.009648 0.019296 0.038592 } \
        delay_fin32_7x7_xp67
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00135 0.0027 0.0054 0.0108 0.0216 0.0432 0.0864 } \
        delay_fin32_7x7_1p5
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0018 0.0036 0.0072 0.0144 0.0288 0.0576 0.1152 } \
        delay_fin32_7x7_x2
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0036 0.0072 0.0144 0.0288 0.0576 0.1152 0.2304 } \
        delay_fin32_7x7_x4
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0045 0.009 0.018 0.036 0.072 0.144 0.288 } \
        delay_fin32_7x7_x5
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0054 0.0108 0.0216 0.0432 0.0864 0.1728 0.3456 } \
        delay_fin32_7x7_x6
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0072 0.0144 0.0288 0.0576 0.1152 0.2304 0.4608 } \
        delay_fin32_7x7_x8
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.009 0.018 0.036 0.072 0.144 0.288 0.576 } \
        delay_fin32_7x7_x10
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0099 0.0198 0.0396 0.0792 0.1584 0.3168 0.6336 } \
        delay_fin32_7x7_x11
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0108 0.0216 0.0432 0.0864 0.1728 0.3456 0.6912 } \
        delay_fin32_7x7_x12
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0117 0.0234 0.0468 0.0936 0.1872 0.3744 0.7488 } \
        delay_fin32_7x7_x13
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0144 0.0288 0.0576 0.1152 0.2304 0.4608 0.9216 } \
        delay_fin32_7x7_x16
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0216 0.0432 0.0864 0.1728 0.3456 0.6912 1.3824 } \
        delay_fin32_7x7_x24
	#fin22 delay
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00072 0.00144 0.00288 0.00576 0.01152 0.02304 0.04608 } \
        delay_fin22_7x7_x1
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.000144 0.000288 0.000576 0.001152 0.002304 0.004608 0.009216 } \
        delay_fin22_7x7_xp2
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00018 0.00036 0.00072 0.00144 0.00288 0.00576 0.01152 } \
        delay_fin22_7x7_xp25
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0002376 0.0004752 0.0009504 0.0019008 0.0038016 0.0076032 0.0152064 } \
        delay_fin22_7x7_xp33
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00036 0.00072 0.00144 0.00288 0.00576 0.01152 0.02304 } \
        delay_fin22_7x7_xp5
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0004824 0.0009648 0.0019296 0.0038592 0.0077184 0.0154368 0.0308736 } \
        delay_fin22_7x7_xp67
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00108 0.00216 0.00432 0.00864 0.01728 0.03456 0.06912 } \
        delay_fin22_7x7_1p5
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00144 0.00288 0.00576 0.01152 0.02304 0.04608 0.09216 } \
        delay_fin22_7x7_x2
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00288 0.00576 0.01152 0.02304 0.04608 0.09216 0.18432 } \
        delay_fin22_7x7_x4
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0036 0.0072 0.0144 0.0288 0.0576 0.1152 0.2304 } \
        delay_fin22_7x7_x5
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00432 0.00864 0.01728 0.03456 0.06912 0.13824 0.27648 } \
        delay_fin22_7x7_x6
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00576 0.01152 0.02304 0.04608 0.09216 0.18432 0.36864 } \
        delay_fin22_7x7_x8
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0072 0.0144 0.0288 0.0576 0.1152 0.2304 0.4608 } \
        delay_fin22_7x7_x10
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00792 0.01584 0.03168 0.06336 0.12672 0.25344 0.50688 } \
        delay_fin22_7x7_x11
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00864 0.01728 0.03456 0.06912 0.13824 0.27648 0.55296 } \
        delay_fin22_7x7_x12
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00936 0.01872 0.03744 0.07488 0.14976 0.29952 0.59904 } \
        delay_fin22_7x7_x13
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.01152 0.02304 0.04608 0.09216 0.18432 0.36864 0.73728 } \
        delay_fin22_7x7_x16
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.01728 0.03456 0.06912 0.13824 0.27648 0.55296 1.10592 } \
        delay_fin22_7x7_x24
	#fin21 delay
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00054 0.00108 0.00216 0.00432 0.00864 0.01728 0.03456 } \
        delay_fin21_7x7_x1
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.000108 0.000216 0.000432 0.000864 0.001728 0.003456 0.006912 } \
        delay_fin21_7x7_xp2
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.000135 0.00027 0.00054 0.00108 0.00216 0.00432 0.00864 } \
        delay_fin21_7x7_xp25
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0001782 0.0003564 0.0007128 0.0014256 0.0028512 0.0057024 0.0114048 } \
        delay_fin21_7x7_xp33
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00027 0.00054 0.00108 0.00216 0.00432 0.00864 0.01728 } \
        delay_fin21_7x7_xp5
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0003618 0.0007236 0.0014472 0.0028944 0.0057888 0.0115776 0.0231552 } \
        delay_fin21_7x7_xp67
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00081 0.00162 0.00324 0.00648 0.01296 0.02592 0.05184 } \
        delay_fin21_7x7_1p5
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00108 0.00216 0.00432 0.00864 0.01728 0.03456 0.06912 } \
        delay_fin21_7x7_x2
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00216 0.00432 0.00864 0.01728 0.03456 0.06912 0.13824 } \
        delay_fin21_7x7_x4
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0027 0.0054 0.0108 0.0216 0.0432 0.0864 0.1728 } \
        delay_fin21_7x7_x5
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00324 0.00648 0.01296 0.02592 0.05184 0.10368 0.20736 } \
        delay_fin21_7x7_x6
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00432 0.00864 0.01728 0.03456 0.06912 0.13824 0.27648 } \
        delay_fin21_7x7_x8
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0054 0.0108 0.0216 0.0432 0.0864 0.1728 0.3456 } \
        delay_fin21_7x7_x10
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00594 0.01188 0.02376 0.04752 0.09504 0.19008 0.38016 } \
        delay_fin21_7x7_x11
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00648 0.01296 0.02592 0.05184 0.10368 0.20736 0.41472 } \
        delay_fin21_7x7_x12
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00702 0.01404 0.02808 0.05616 0.11232 0.22464 0.44928 } \
        delay_fin21_7x7_x13
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00864 0.01728 0.03456 0.06912 0.13824 0.27648 0.55296 } \
        delay_fin21_7x7_x16
define_template -type delay \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.01296 0.02592 0.05184 0.10368 0.20736 0.41472 0.82944 } \
        delay_fin21_7x7_x24
		
# power
	#fin32 power
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0009 0.0018 0.0036 0.0072 0.0144 0.0288 0.0576 } \
        power_fin32_7x7_x1
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00018 0.00036 0.00072 0.00144 0.00288 0.00576 0.01152 } \
        power_fin32_7x7_xp2
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.000225 0.00045 0.0009 0.0018 0.0036 0.0072 0.0144 } \
        power_fin32_7x7_xp25
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.000297 0.000594 0.001188 0.002376 0.004752 0.009504 0.019008 } \
        power_fin32_7x7_xp33
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00045 0.0009 0.0018 0.0036 0.0072 0.0144 0.0288 } \
        power_fin32_7x7_xp5
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.000603 0.001206 0.002412 0.004824 0.009648 0.019296 0.038592 } \
        power_fin32_7x7_xp67
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00135 0.0027 0.0054 0.0108 0.0216 0.0432 0.0864 } \
        power_fin32_7x7_1p5
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0018 0.0036 0.0072 0.0144 0.0288 0.0576 0.1152 } \
        power_fin32_7x7_x2
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0036 0.0072 0.0144 0.0288 0.0576 0.1152 0.2304 } \
        power_fin32_7x7_x4
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0045 0.009 0.018 0.036 0.072 0.144 0.288 } \
        power_fin32_7x7_x5
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0054 0.0108 0.0216 0.0432 0.0864 0.1728 0.3456 } \
        power_fin32_7x7_x6
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0072 0.0144 0.0288 0.0576 0.1152 0.2304 0.4608 } \
        power_fin32_7x7_x8
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.009 0.018 0.036 0.072 0.144 0.288 0.576 } \
        power_fin32_7x7_x10
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0099 0.0198 0.0396 0.0792 0.1584 0.3168 0.6336 } \
        power_fin32_7x7_x11
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0108 0.0216 0.0432 0.0864 0.1728 0.3456 0.6912 } \
        power_fin32_7x7_x12
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0117 0.0234 0.0468 0.0936 0.1872 0.3744 0.7488 } \
        power_fin32_7x7_x13
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0144 0.0288 0.0576 0.1152 0.2304 0.4608 0.9216 } \
        power_fin32_7x7_x16
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0216 0.0432 0.0864 0.1728 0.3456 0.6912 1.3824 } \
        power_fin32_7x7_x24
	#fin22 power
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00072 0.00144 0.00288 0.00576 0.01152 0.02304 0.04608 } \
        power_fin22_7x7_x1
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.000144 0.000288 0.000576 0.001152 0.002304 0.004608 0.009216 } \
        power_fin22_7x7_xp2
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00018 0.00036 0.00072 0.00144 0.00288 0.00576 0.01152 } \
        power_fin22_7x7_xp25
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0002376 0.0004752 0.0009504 0.0019008 0.0038016 0.0076032 0.0152064 } \
        power_fin22_7x7_xp33
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00036 0.00072 0.00144 0.00288 0.00576 0.01152 0.02304 } \
        power_fin22_7x7_xp5
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0004824 0.0009648 0.0019296 0.0038592 0.0077184 0.0154368 0.0308736 } \
        power_fin22_7x7_xp67
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00108 0.00216 0.00432 0.00864 0.01728 0.03456 0.06912 } \
        power_fin22_7x7_1p5
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00144 0.00288 0.00576 0.01152 0.02304 0.04608 0.09216 } \
        power_fin22_7x7_x2
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00288 0.00576 0.01152 0.02304 0.04608 0.09216 0.18432 } \
        power_fin22_7x7_x4
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0036 0.0072 0.0144 0.0288 0.0576 0.1152 0.2304 } \
        power_fin22_7x7_x5
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00432 0.00864 0.01728 0.03456 0.06912 0.13824 0.27648 } \
        power_fin22_7x7_x6
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00576 0.01152 0.02304 0.04608 0.09216 0.18432 0.36864 } \
        power_fin22_7x7_x8
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0072 0.0144 0.0288 0.0576 0.1152 0.2304 0.4608 } \
        power_fin22_7x7_x10
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00792 0.01584 0.03168 0.06336 0.12672 0.25344 0.50688 } \
        power_fin22_7x7_x11
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00864 0.01728 0.03456 0.06912 0.13824 0.27648 0.55296 } \
        power_fin22_7x7_x12
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00936 0.01872 0.03744 0.07488 0.14976 0.29952 0.59904 } \
        power_fin22_7x7_x13
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.01152 0.02304 0.04608 0.09216 0.18432 0.36864 0.73728 } \
        power_fin22_7x7_x16
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.01728 0.03456 0.06912 0.13824 0.27648 0.55296 1.10592 } \
        power_fin22_7x7_x24
	#fin21 power
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00054 0.00108 0.00216 0.00432 0.00864 0.01728 0.03456 } \
        power_fin21_7x7_x1
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.000108 0.000216 0.000432 0.000864 0.001728 0.003456 0.006912 } \
        power_fin21_7x7_xp2
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.000135 0.00027 0.00054 0.00108 0.00216 0.00432 0.00864 } \
        power_fin21_7x7_xp25
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0001782 0.0003564 0.0007128 0.0014256 0.0028512 0.0057024 0.0114048 } \
        power_fin21_7x7_xp33
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00027 0.00054 0.00108 0.00216 0.00432 0.00864 0.01728 } \
        power_fin21_7x7_xp5
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0003618 0.0007236 0.0014472 0.0028944 0.0057888 0.0115776 0.0231552 } \
        power_fin21_7x7_xp67
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00081 0.00162 0.00324 0.00648 0.01296 0.02592 0.05184 } \
        power_fin21_7x7_1p5
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00108 0.00216 0.00432 0.00864 0.01728 0.03456 0.06912 } \
        power_fin21_7x7_x2
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00216 0.00432 0.00864 0.01728 0.03456 0.06912 0.13824 } \
        power_fin21_7x7_x4
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0027 0.0054 0.0108 0.0216 0.0432 0.0864 0.1728 } \
        power_fin21_7x7_x5
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00324 0.00648 0.01296 0.02592 0.05184 0.10368 0.20736 } \
        power_fin21_7x7_x6
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00432 0.00864 0.01728 0.03456 0.06912 0.13824 0.27648 } \
        power_fin21_7x7_x8
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.0054 0.0108 0.0216 0.0432 0.0864 0.1728 0.3456 } \
        power_fin21_7x7_x10
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00594 0.01188 0.02376 0.04752 0.09504 0.19008 0.38016 } \
        power_fin21_7x7_x11
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00648 0.01296 0.02592 0.05184 0.10368 0.20736 0.41472 } \
        power_fin21_7x7_x12
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00702 0.01404 0.02808 0.05616 0.11232 0.22464 0.44928 } \
        power_fin21_7x7_x13
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.00864 0.01728 0.03456 0.06912 0.13824 0.27648 0.55296 } \
        power_fin21_7x7_x16
define_template -type power \
        -index_1 {0.005 0.01 0.02 0.04 0.08 0.16 0.32 } \
        -index_2 {0.01296 0.02592 0.05184 0.10368 0.20736 0.41472 0.82944 } \
        power_fin21_7x7_x24

if {[ALAPI_active_cell "A2O1A1Ixp33_fin22"]} {
define_cell \
       -input { A1 A2 B C } \
       -output { Y } \
       -pinlist { A1 A2 B C Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       A2O1A1Ixp33_fin22

}

if {[ALAPI_active_cell "A2O1A1O1Ixp25_fin22"]} {
define_cell \
       -input { A1 A2 B C D } \
       -output { Y } \
       -pinlist { A1 A2 B C D Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       A2O1A1O1Ixp25_fin22

}
	
if {[ALAPI_active_cell "AO211x2_fin22"]} {
define_cell \
       -input { A1 A2 B C } \
       -output { Y } \
       -pinlist { A1 A2 B C Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AO211x2_fin22

}

if {[ALAPI_active_cell "AO21x1_fin22"]} {
define_cell \
       -input { A1 A2 B } \
       -output { Y } \
       -pinlist { A1 A2 B Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AO21x1_fin22

}

if {[ALAPI_active_cell "AO21x2_fin22"]} {
define_cell \
       -input { A1 A2 B } \
       -output { Y } \
       -pinlist { A1 A2 B Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AO21x2_fin22

}

if {[ALAPI_active_cell "AO221x1_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AO221x1_fin22

}

if {[ALAPI_active_cell "AO221x2_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AO221x2_fin22

}

if {[ALAPI_active_cell "AO222x1_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C1 C2 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AO222x1_fin22

}

if {[ALAPI_active_cell "AO222x2_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C1 C2 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AO222x2_fin22

}

if {[ALAPI_active_cell "AO22x1_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AO22x1_fin22

}

if {[ALAPI_active_cell "AO22x2_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AO22x2_fin22

}

if {[ALAPI_active_cell "AO31x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B } \
       -output { Y } \
       -pinlist { A1 A2 A3 B Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AO31x1_fin22

}


if {[ALAPI_active_cell "AO31x2_fin22"]} {
define_cell \
       -input { A1 A2 A3 B } \
       -output { Y } \
       -pinlist { A1 A2 A3 B Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AO31x2_fin22

}

if {[ALAPI_active_cell "AO322x2_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 C1 C2 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AO322x2_fin22

}

if {[ALAPI_active_cell "AO32x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AO32x1_fin22

}

if {[ALAPI_active_cell "AO32x2_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AO32x2_fin22

}

if {[ALAPI_active_cell "AO331x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AO331x1_fin22

}

if {[ALAPI_active_cell "AO331x2_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AO331x2_fin22

}

if {[ALAPI_active_cell "AO332x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 C2 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AO332x1_fin22

}

if {[ALAPI_active_cell "AO332x2_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 C2 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AO332x2_fin22

}

if {[ALAPI_active_cell "AO333x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 C2 C3 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 C2 C3 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AO333x1_fin22

}

if {[ALAPI_active_cell "AO333x2_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 C2 C3 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 C2 C3 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AO333x2_fin22

}

if {[ALAPI_active_cell "AO33x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AO33x1_fin22

}


if {[ALAPI_active_cell "AO33x2_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AO33x2_fin22

}

if {[ALAPI_active_cell "AOI211x1_fin22"]} {
define_cell \
       -input { A1 A2 B C } \
       -output { Y } \
       -pinlist { A1 A2 B C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AOI211x1_fin22

}


if {[ALAPI_active_cell "AOI211xp25_fin22"]} {
define_cell \
       -input { A1 A2 B C } \
       -output { Y } \
       -pinlist { A1 A2 B C Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       AOI211xp25_fin22

}

if {[ALAPI_active_cell "AOI21x1_fin22"]} {
define_cell \
       -input { A1 A2 B } \
       -output { Y } \
       -pinlist { A1 A2 B Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AOI21x1_fin22

}

if {[ALAPI_active_cell "AOI21xp5_fin22"]} {
define_cell \
       -input { A1 A2 B } \
       -output { Y } \
       -pinlist { A1 A2 B Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       AOI21xp5_fin22

}


if {[ALAPI_active_cell "AOI21xp25_fin22"]} {
define_cell \
       -input { A1 A2 B } \
       -output { Y } \
       -pinlist { A1 A2 B Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       AOI21xp25_fin22

}

if {[ALAPI_active_cell "AOI221x1_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AOI221x1_fin22

}


if {[ALAPI_active_cell "AOI222xp25_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C1 C2 Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       AOI222xp25_fin22

}


if {[ALAPI_active_cell "AOI221xp25_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       AOI221xp25_fin22

}


if {[ALAPI_active_cell "AOI22x1_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AOI22x1_fin22

}


if {[ALAPI_active_cell "AOI22xp25_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       AOI22xp25_fin22

}


if {[ALAPI_active_cell "AOI22xp5_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       AOI22xp5_fin22

}

if {[ALAPI_active_cell "AOI311xp33_fin22"]} {
define_cell \
       -input { A1 A2 A3 B C } \
       -output { Y } \
       -pinlist { A1 A2 A3 B C Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       AOI311xp33_fin22

}

if {[ALAPI_active_cell "AOI31xp25_fin22"]} {
define_cell \
       -input { A1 A2 A3 B } \
       -output { Y } \
       -pinlist { A1 A2 A3 B Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       AOI31xp25_fin22

}

if {[ALAPI_active_cell "AOI31xp5_fin22"]} {
define_cell \
       -input { A1 A2 A3 B } \
       -output { Y } \
       -pinlist { A1 A2 A3 B Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       AOI31xp5_fin22

}

if {[ALAPI_active_cell "AOI321xp25_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 C } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 C Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       AOI321xp25_fin22

}

if {[ALAPI_active_cell "AOI322xp25_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 C1 C2 Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       AOI322xp25_fin22

}

if {[ALAPI_active_cell "AOI32x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2} \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AOI32x1_fin22

}


if {[ALAPI_active_cell "AOI32xp33_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2} \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       AOI32xp33_fin22

}

if {[ALAPI_active_cell "AOI32xp25_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2} \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       AOI32xp25_fin22

}


if {[ALAPI_active_cell "AOI331xp33_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       AOI331xp33_fin22

}

if {[ALAPI_active_cell "AOI332xp33_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 C2 Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       AOI332xp33_fin22

}

if {[ALAPI_active_cell "AOI333xp33_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 C2 C3 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 C2 C3 Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       AOI333xp33_fin22

}

if {[ALAPI_active_cell "AOI33x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AOI33x1_fin22

}


if {[ALAPI_active_cell "AOI33xp33_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       AOI33xp33_fin22

}



 
if {[ALAPI_active_cell "BUFx10_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x10 \
       -power power_fin22_7x7_x10 \
       BUFx10_fin22

}


if {[ALAPI_active_cell "BUFx12_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x12 \
       -power power_fin22_7x7_x12 \
       BUFx12_fin22

}

if {[ALAPI_active_cell "BUFx12f_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x12 \
       -power power_fin22_7x7_x12 \
       BUFx12f_fin22

}

if {[ALAPI_active_cell "BUFx16f_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x16 \
       -power power_fin22_7x7_x16 \
       BUFx16f_fin22

}

if {[ALAPI_active_cell "BUFx24_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x24 \
       -power power_fin22_7x7_x24 \
       BUFx24_fin22

}

if {[ALAPI_active_cell "BUFx2_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       BUFx2_fin22

}

if {[ALAPI_active_cell "BUFx3_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       BUFx3_fin22

}

if {[ALAPI_active_cell "BUFx4_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       BUFx4_fin22

}

if {[ALAPI_active_cell "BUFx4f_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       BUFx4f_fin22

}

if {[ALAPI_active_cell "BUFx5_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x5 \
       -power power_fin22_7x7_x5 \
       BUFx5_fin22

}

if {[ALAPI_active_cell "BUFx6f_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x6 \
       -power power_fin22_7x7_x6 \
       BUFx6f_fin22

}

if {[ALAPI_active_cell "BUFx8_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x8 \
       -power power_fin22_7x7_x8 \
       BUFx8_fin22

}

if {[ALAPI_active_cell "HB1xp5_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       HB1xp5_fin22

}

if {[ALAPI_active_cell "HB2xp5_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       HB2xp5_fin22

}

if {[ALAPI_active_cell "HB3xp5_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       HB3xp5_fin22

}

if {[ALAPI_active_cell "HB4xp5_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       HB4xp5_fin22

}

if {[ALAPI_active_cell "INVx11_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x11 \
       -power power_fin22_7x7_x11 \
       INVx11_fin22

}

if {[ALAPI_active_cell "INVx13_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x13 \
       -power power_fin22_7x7_x13 \
       INVx13_fin22

}

if {[ALAPI_active_cell "INVx1_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       INVx1_fin22

}

if {[ALAPI_active_cell "INVx2_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       INVx2_fin22

}

if {[ALAPI_active_cell "INVx3_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       INVx3_fin22

}

if {[ALAPI_active_cell "INVx4_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       INVx4_fin22

}

if {[ALAPI_active_cell "INVx5_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x5 \
       -power power_fin22_7x7_x5 \
       INVx5_fin22

}

if {[ALAPI_active_cell "INVx6_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x6 \
       -power power_fin22_7x7_x6 \
       INVx6_fin22

}

if {[ALAPI_active_cell "INVx8_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x8 \
       -power power_fin22_7x7_x8 \
       INVx8_fin22

}

if {[ALAPI_active_cell "INVxp5_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       INVxp5_fin22

}

if {[ALAPI_active_cell "O2A1O1Ixp33_fin22"]} {
define_cell \
       -input { A1 A2 B C } \
       -output { Y } \
       -pinlist { A1 A2 B C Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       O2A1O1Ixp33_fin22

}


if {[ALAPI_active_cell "O2A1O1Ixp5_fin22"]} {
define_cell \
       -input { A1 A2 B C } \
       -output { Y } \
       -pinlist { A1 A2 B C Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       O2A1O1Ixp5_fin22

}

if {[ALAPI_active_cell "OA211x1_fin22"]} {
define_cell \
       -input { A1 A2 B C } \
       -output { Y } \
       -pinlist { A1 A2 B C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OA211x1_fin22

}


if {[ALAPI_active_cell "OA211x2_fin22"]} {
define_cell \
       -input { A1 A2 B C } \
       -output { Y } \
       -pinlist { A1 A2 B C Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OA211x2_fin22

}

if {[ALAPI_active_cell "OA21x2_fin22"]} {
define_cell \
       -input { A1 A2 B } \
       -output { Y } \
       -pinlist { A1 A2 B Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OA21x2_fin22

}

if {[ALAPI_active_cell "OA221x1_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OA221x1_fin22

}



if {[ALAPI_active_cell "OA221x2_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OA221x2_fin22

}

if {[ALAPI_active_cell "OA222x1_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C1 C2 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OA222x1_fin22

}

if {[ALAPI_active_cell "OA222x2_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C1 C2 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OA222x2_fin22

}

if {[ALAPI_active_cell "OA22x2_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OA22x2_fin22

}

if {[ALAPI_active_cell "OA31x2_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OA31x2_fin22

}


if {[ALAPI_active_cell "OA331x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OA331x1_fin22

}

if {[ALAPI_active_cell "OA331x2_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OA331x2_fin22

}

if {[ALAPI_active_cell "OA332x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 C2 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OA332x1_fin22

}

if {[ALAPI_active_cell "OA332x2_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 C2 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OA332x2_fin22

}

if {[ALAPI_active_cell "OA333x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 C2 C3} \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 C2 C3 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OA333x1_fin22

}

if {[ALAPI_active_cell "OA333x2_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 C2 C3 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 C2 C3 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OA333x2_fin22

}


if {[ALAPI_active_cell "OA33x2_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OA33x2_fin22

}

if {[ALAPI_active_cell "OAI211x1_fin22"]} {
define_cell \
       -input { A1 A2 B C } \
       -output { Y } \
       -pinlist { A1 A2 B C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OAI211x1_fin22

}

if {[ALAPI_active_cell "OAI211xp25_fin22"]} {
define_cell \
       -input { A1 A2 B C } \
       -output { Y } \
       -pinlist { A1 A2 B C Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       OAI211xp25_fin22

}




if {[ALAPI_active_cell "OAI21x1_fin22"]} {
define_cell \
       -input { A1 A2 B } \
       -output { Y } \
       -pinlist { A1 A2 B Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OAI21x1_fin22

}

if {[ALAPI_active_cell "OAI21xp5_fin22"]} {
define_cell \
       -input { A1 A2 B } \
       -output { Y } \
       -pinlist { A1 A2 B Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       OAI21xp5_fin22

}


if {[ALAPI_active_cell "OAI21xp25_fin22"]} {
define_cell \
       -input { A1 A2 B } \
       -output { Y } \
       -pinlist { A1 A2 B Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       OAI21xp25_fin22
}


if {[ALAPI_active_cell "OAI221x1_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OAI221x1_fin22

}


if {[ALAPI_active_cell "OAI221xp25_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       OAI221xp25_fin22

}

if {[ALAPI_active_cell "OAI222xp25_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 C1 C2 Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       OAI222xp25_fin22

}

if {[ALAPI_active_cell "OAI22x1_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OAI22x1_fin22

}

if {[ALAPI_active_cell "OAI22xp5_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       OAI22xp5_fin22

}

if {[ALAPI_active_cell "OAI22xp25_fin22"]} {
define_cell \
       -input { A1 A2 B1 B2 } \
       -output { Y } \
       -pinlist { A1 A2 B1 B2 Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       OAI22xp25_fin22

}

if {[ALAPI_active_cell "OAI311xp33_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 C1 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 C1 Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       OAI311xp33_fin22

}

if {[ALAPI_active_cell "OAI31xp5_fin22"]} {
define_cell \
       -input { A1 A2 A3 B } \
       -output { Y } \
       -pinlist { A1 A2 A3 B Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       OAI31xp5_fin22

}


if {[ALAPI_active_cell "OAI31xp25_fin22"]} {
define_cell \
       -input { A1 A2 A3 B } \
       -output { Y } \
       -pinlist { A1 A2 A3 B Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       OAI31xp25_fin22

}


if {[ALAPI_active_cell "OAI321xp25_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 C } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 C Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       OAI321xp25_fin22

}


if {[ALAPI_active_cell "OAI322xp25_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 C1 C2 Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       OAI322xp25_fin22

}


if {[ALAPI_active_cell "OAI32xp33_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2} \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       OAI32xp33_fin22

}


if {[ALAPI_active_cell "OAI32xp25_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2} \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       OAI32xp25_fin22

}


if {[ALAPI_active_cell "OAI32x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2} \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OAI32x1_fin22

}

if {[ALAPI_active_cell "OAI331xp33_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       OAI331xp33_fin22

}

if {[ALAPI_active_cell "OAI332xp33_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 C2 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 C2 Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       OAI332xp33_fin22

}

if {[ALAPI_active_cell "OAI333xp33_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 C1 C2 C3 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 C1 C2 C3 Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       OAI333xp33_fin22

}

if {[ALAPI_active_cell "OAI33xp33_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       OAI33xp33_fin22

}


if {[ALAPI_active_cell "OAI33x1_fin22"]} {
define_cell \
       -input { A1 A2 A3 B1 B2 B3 } \
       -output { Y } \
       -pinlist { A1 A2 A3 B1 B2 B3 Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OAI33x1_fin22
}


if {[ALAPI_active_cell "ASYNC_reset_DFFHx1_fin22"]} {
define_cell \
	   -clock { CLK } \
       -async { RESET } \
       -input { D } \
       -output { QN } \
       -pinlist { CLK RESET D QN } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
	   -constraint constraint_fin22_7x7 \
       ASYNC_reset_DFFHx1_fin22

}


if {[ALAPI_active_cell "ASYNC_set_DFFHx1_fin22"]} {
define_cell \
	   -clock { CLK } \
       -async { SET } \
       -input { D } \
       -output { QN } \
       -pinlist { CLK SET D QN } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
	   -constraint constraint_fin22_7x7 \
       ASYNC_set_DFFHx1_fin22

}


if {[ALAPI_active_cell "DFFHQNx1_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { QN } \
       -pinlist { CLK D QN } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
	   -constraint constraint_fin22_7x7 \
       DFFHQNx1_fin22

}

if {[ALAPI_active_cell "DFFHQNx2_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { QN } \
       -pinlist { CLK D QN } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
	   -constraint constraint_fin22_7x7 \
       DFFHQNx2_fin22

}

if {[ALAPI_active_cell "DFFHQx3_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { QN } \
       -pinlist { CLK D QN } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
	   -constraint constraint_fin22_7x7 \
       DFFHQNx3_fin22

}

if {[ALAPI_active_cell "DFFHQx4_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D Q } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
	   -constraint constraint_fin22_7x7 \
       DFFHQx4_fin22

}

if {[ALAPI_active_cell "DFFLQNx1_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { QN } \
       -pinlist { CLK D QN } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
	   -constraint constraint_fin22_7x7 \
       DFFLQNx1_fin22

}

if {[ALAPI_active_cell "DFFLQNx2_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { QN } \
       -pinlist { CLK D QN } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
	   -constraint constraint_fin22_7x7 \
       DFFLQNx2_fin22

}

if {[ALAPI_active_cell "DFFLQNx3_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { QN } \
       -pinlist { CLK D QN } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
	   -constraint constraint_fin22_7x7 \
       DFFLQNx3_fin22

}

if {[ALAPI_active_cell "DFFLQx4_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D Q } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
	   -constraint constraint_fin22_7x7 \
       DFFLQx4_fin22

}

if {[ALAPI_active_cell "DHLx1_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D Q } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
	   -constraint constraint_fin22_7x7 \
       DHLx1_fin22

}

if {[ALAPI_active_cell "DHLx2_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D Q } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
	   -constraint constraint_fin22_7x7 \
       DHLx2_fin22

}

if {[ALAPI_active_cell "DHLx3_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D Q } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
	   -constraint constraint_fin22_7x7 \
       DHLx3_fin22

}

if {[ALAPI_active_cell "DLLx1_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D Q } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
	   -constraint constraint_fin22_7x7 \
       DLLx1_fin22

}

if {[ALAPI_active_cell "DLLx2_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D Q } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
	   -constraint constraint_fin22_7x7 \
       DLLx2_fin22

}

if {[ALAPI_active_cell "DLLx3_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D Q } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
	   -constraint constraint_fin22_7x7 \
       DLLx3_fin22

}

if {[ALAPI_active_cell "SDFHx1_fin22"]} {
define_cell \
	   -clock { CLK } \
       -input { D SE SI } \
       -output { QN } \
       -pinlist { CLK SE SI D QN } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
	   -constraint constraint_fin22_7x7 \
       SDFHx1_fin22

}


if {[ALAPI_active_cell "SDFHx2_fin22"]} {
define_cell \
	   -clock { CLK } \
       -input { D SE SI } \
       -output { QN } \
       -pinlist { CLK SE SI D QN } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
	   -constraint constraint_fin22_7x7 \
       SDFHx2_fin22

}

if {[ALAPI_active_cell "SDFHx3_fin22"]} {
define_cell \
	   -clock { CLK } \
       -input { D SE SI } \
       -output { QN } \
       -pinlist { CLK SE SI D QN } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
	   -constraint constraint_fin22_7x7 \
       SDFHx3_fin22

}


if {[ALAPI_active_cell "SDFHx4_fin22"]} {
define_cell \
	   -clock { CLK } \
       -input { D SE SI } \
       -output { QN } \
       -pinlist { CLK SE SI D QN } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
	   -constraint constraint_fin22_7x7 \
       SDFHx4_fin22

}


if {[ALAPI_active_cell "SDFLx1_fin22"]} {
define_cell \
	   -clock { CLK } \
       -input { D SE SI } \
       -output { QN } \
       -pinlist { CLK SE SI D QN } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
	   -constraint constraint_fin22_7x7 \
       SDFLx1_fin22

}


if {[ALAPI_active_cell "SDFLx2_fin22"]} {
define_cell \
	   -clock { CLK } \
       -input { D SE SI } \
       -output { QN } \
       -pinlist { CLK SE SI D QN } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
	   -constraint constraint_fin22_7x7 \
       SDFLx2_fin22

}

if {[ALAPI_active_cell "SDFLx3_fin22"]} {
define_cell \
	   -clock { CLK } \
       -input { D SE SI } \
       -output { QN } \
       -pinlist { CLK SE SI D QN } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
	   -constraint constraint_fin22_7x7 \
       SDFLx3_fin22

}


if {[ALAPI_active_cell "SDFLx4_fin22"]} {
define_cell \
	   -clock { CLK } \
       -input { D SE SI } \
       -output { QN } \
       -pinlist { CLK SE SI D QN } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
	   -constraint constraint_fin22_7x7 \
       SDFLx4_fin22

}

if {[ALAPI_active_cell "AND2x1_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AND2x1_fin22

}
		 
	 
if {[ALAPI_active_cell "AND2x2_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AND2x2_fin22

}


if {[ALAPI_active_cell "AND2x4_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       AND2x4_fin22

}

if {[ALAPI_active_cell "AND2x6_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x6 \
       -power power_fin22_7x7_x6 \
       AND2x6_fin22

}

if {[ALAPI_active_cell "AND3x1_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AND3x1_fin22

}

if {[ALAPI_active_cell "AND3x2_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AND3x2_fin22

}

if {[ALAPI_active_cell "AND3x4_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       AND3x4_fin22

}

if {[ALAPI_active_cell "AND3x6_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x6 \
       -power power_fin22_7x7_x6 \
       AND3x6_fin22

}

if {[ALAPI_active_cell "AND4x1_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AND4x1_fin22

}

if {[ALAPI_active_cell "AND4x2_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AND4x2_fin22

}

if {[ALAPI_active_cell "AND4x4_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       AND4x4_fin22

}

if {[ALAPI_active_cell "AND4x6_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x6 \
       -power power_fin22_7x7_x6 \
       AND4x6_fin22

}

if {[ALAPI_active_cell "AND5x1_fin22"]} {
define_cell \
       -input { A B C D E } \
       -output { Y } \
       -pinlist { A B C D E Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       AND5x1_fin22

}

if {[ALAPI_active_cell "AND5x2_fin22"]} {
define_cell \
       -input { A B C D E } \
       -output { Y } \
       -pinlist { A B C D E Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       AND5x2_fin22

}

if {[ALAPI_active_cell "FAx1_fin22"]} {
define_cell \
       -input { A B CI } \
       -output { CON SN } \
       -pinlist { A B CI CON SN } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       FAx1_fin22

}
if {[ALAPI_active_cell "HAx1_fin22"]} {
define_cell \
       -input { A B } \
       -output { CON SN } \
       -pinlist { A B CON SN } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       HAx1_fin22

}
if {[ALAPI_active_cell "HAxp5_fin22"]} {
define_cell \
       -input { A B } \
       -output { CON SN } \
       -pinlist { A B CON SN } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       HAxp5_fin22

}

if {[ALAPI_active_cell "MAJIxp5_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       MAJIxp5_fin22

}

if {[ALAPI_active_cell "MAJx2_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       MAJx2_fin22

}


if {[ALAPI_active_cell "MAJx3_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       MAJx3_fin22

}


if {[ALAPI_active_cell "MUX2x1_fin22"]} {
define_cell \
       -input { A B S } \
       -output { O } \
       -pinlist { A B S O } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       MUX2x1_fin22

}


if {[ALAPI_active_cell "MUX2x2_fin22"]} {
define_cell \
       -input { A B S } \
       -output { Z } \
       -pinlist { A B S Z } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       MUX2x2_fin22

}

if {[ALAPI_active_cell "NAND2x1_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       NAND2x1_fin22

}

if {[ALAPI_active_cell "NAND2x1p5_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_1p5 \
       -power power_fin22_7x7_1p5 \
       NAND2x1p5_fin22

}

if {[ALAPI_active_cell "NAND2x2_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       NAND2x2_fin22

}

if {[ALAPI_active_cell "NAND2xp25_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       NAND2xp25_fin22

}

if {[ALAPI_active_cell "NAND2xp5_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       NAND2xp5_fin22

}

if {[ALAPI_active_cell "NAND2xp33_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       NAND2xp33_fin22

}

if {[ALAPI_active_cell "NAND3x1_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       NAND3x1_fin22

}

if {[ALAPI_active_cell "NAND3x2_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       NAND3x2_fin22

}

if {[ALAPI_active_cell "NAND3xp33_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       NAND3xp33_fin22

}

if {[ALAPI_active_cell "NAND4xp25_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       NAND4xp25_fin22

}


if {[ALAPI_active_cell "NAND4x1_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       NAND4x1_fin22

}


if {[ALAPI_active_cell "NAND4x2_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       NAND4x2_fin22

}



if {[ALAPI_active_cell "NAND4xp75_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       NAND4xp75_fin22

}

if {[ALAPI_active_cell "NAND5xp2_fin22"]} {
define_cell \
       -input { A B C D E } \
       -output { Y } \
       -pinlist { A B C D E Y } \
       -delay delay_fin22_7x7_xp2 \
       -power power_fin22_7x7_xp2 \
       NAND5xp2_fin22

}

if {[ALAPI_active_cell "NOR2x1_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       NOR2x1_fin22

}


if {[ALAPI_active_cell "NOR2xp33_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       NOR2xp33_fin22

}

if {[ALAPI_active_cell "NOR2x1p5_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_1p5 \
       -power power_fin22_7x7_1p5 \
       NOR2x1p5_fin22

}

if {[ALAPI_active_cell "NOR2x2_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       NOR2x2_fin22

}

if {[ALAPI_active_cell "NOR2xp25_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_xp25 \
       -power power_fin22_7x7_xp25 \
       NOR2xp25_fin22

}

if {[ALAPI_active_cell "NOR2xp5_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       NOR2xp5_fin22

}

if {[ALAPI_active_cell "NOR3x1_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       NOR3x1_fin22

}

if {[ALAPI_active_cell "NOR3x2_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       NOR3x2_fin22

}

if {[ALAPI_active_cell "NOR3xp33_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       NOR3xp33_fin22

}

if {[ALAPI_active_cell "NOR4xp25_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_xp33 \
       -power power_fin22_7x7_xp33 \
       NOR4xp25_fin22

}


if {[ALAPI_active_cell "NOR4x1_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       NOR4x1_fin22

}


if {[ALAPI_active_cell "NOR4x2_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       NOR4x2_fin22

}




if {[ALAPI_active_cell "NOR4xp75_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       NOR4xp75_fin22

}

if {[ALAPI_active_cell "NOR5xp2_fin22"]} {
define_cell \
       -input { A B C D E } \
       -output { Y } \
       -pinlist { A B C D E Y } \
       -delay delay_fin22_7x7_xp2 \
       -power power_fin22_7x7_xp2 \
       NOR5xp2_fin22

}


if {[ALAPI_active_cell "OR2x1_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OR2x1_fin22

}


if {[ALAPI_active_cell "OR2x2_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OR2x2_fin22

}


if {[ALAPI_active_cell "OR2x4_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       OR2x4_fin22

}

if {[ALAPI_active_cell "OR2x6_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x6 \
       -power power_fin22_7x7_x6 \
       OR2x6_fin22

}

if {[ALAPI_active_cell "OR3x1_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OR3x1_fin22

}

if {[ALAPI_active_cell "OR3x2_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OR3x2_fin22

}

if {[ALAPI_active_cell "OR3x4_fin22"]} {
define_cell \
       -input { A B C } \
       -output { Y } \
       -pinlist { A B C Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       OR3x4_fin22

}

if {[ALAPI_active_cell "OR4x1_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OR4x1_fin22

}

if {[ALAPI_active_cell "OR4x2_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OR4x2_fin22

}


if {[ALAPI_active_cell "OR4x4_fin22"]} {
define_cell \
       -input { A B C D } \
       -output { Y } \
       -pinlist { A B C D Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       OR4x4_fin22

}

if {[ALAPI_active_cell "OR5x1_fin22"]} {
define_cell \
       -input { A B C D E } \
       -output { Y } \
       -pinlist { A B C D E Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       OR5x1_fin22

}

if {[ALAPI_active_cell "OR5x2_fin22"]} {
define_cell \
       -input { A B C D E } \
       -output { Y } \
       -pinlist { A B C D E Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       OR5x2_fin22

}


if {[ALAPI_active_cell "OR5x4_fin22"]} {
define_cell \
       -input { A B C D E } \
       -output { Y } \
       -pinlist { A B C D E Y } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
       OR5x4_fin22

}

if {[ALAPI_active_cell "TIEHIx1_fin22"]} {
define_cell \
       -input {  } \
       -output { H } \
       -pinlist { H } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       TIEHIx1_fin22

}

if {[ALAPI_active_cell "TIELOx1_fin22"]} {
define_cell \
       -input {  } \
       -output { L } \
       -pinlist { L } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       TIELOx1_fin22

}

if {[ALAPI_active_cell "XNOR2x1_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       XNOR2x1_fin22

}

if {[ALAPI_active_cell "XNOR2x2_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       XNOR2x2_fin22

}

if {[ALAPI_active_cell "XNOR2xp5_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       XNOR2xp5_fin22

}

if {[ALAPI_active_cell "XOR2x1_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       XOR2x1_fin22

}

if {[ALAPI_active_cell "XOR2x2_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
       XOR2x2_fin22

}

if {[ALAPI_active_cell "XOR2xp5_fin22"]} {
define_cell \
       -input { A B } \
       -output { Y } \
       -pinlist { A B Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       XOR2xp5_fin22

}

if {[ALAPI_active_cell "ICGx1_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { ENA SE } \
       -output { GCLK } \
       -pinlist { CLK ENA SE GCLK } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
	   -constraint constraint_fin22_7x7 \
       ICGx1_fin22
}

if {[ALAPI_active_cell "ICGx2_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { ENA SE } \
       -output { GCLK } \
       -pinlist { CLK ENA SE GCLK } \
       -delay delay_fin22_7x7_x2 \
       -power power_fin22_7x7_x2 \
	   -constraint constraint_fin22_7x7 \
       ICGx2_fin22
}

if {[ALAPI_active_cell "ICGx3_fin22"]} {
define_cell \
       -clock { CLK } \
       -input { ENA SE } \
       -output { GCLK } \
       -pinlist { CLK ENA SE GCLK } \
       -delay delay_fin22_7x7_x4 \
       -power power_fin22_7x7_x4 \
	   -constraint constraint_fin22_7x7 \
       ICGx3_fin22
}
if {[ALAPI_active_cell "BUFx1_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_x1 \
       -power power_fin22_7x7_x1 \
       BUFx1_fin22

}
if {[ALAPI_active_cell "BUFxp5_fin22"]} {
define_cell \
       -input { A } \
       -output { Y } \
       -pinlist { A Y } \
       -delay delay_fin22_7x7_xp5 \
       -power power_fin22_7x7_xp5 \
       BUFxp5_fin22

}
